import { useEffect, useRef, useState } from "react";
import { stops } from "./journey";
const hero = "https://have-a-go-journal.gopinpv3.chatgpt.site/caddo-lake-hero.png";

function Header(){
  const [open,setOpen]=useState(false); const ref=useRef(null);
  useEffect(()=>{const close=e=>!ref.current?.contains(e.target)&&setOpen(false);const esc=e=>e.key==="Escape"&&setOpen(false);document.addEventListener("click",close);document.addEventListener("keydown",esc);return()=>{document.removeEventListener("click",close);document.removeEventListener("keydown",esc)}},[]);
  return <header className="site-header"><a className="brand" href="/"><span className="brand-mark">↗</span> Have a Go</a><div className="journey-menu" ref={ref}><button className="journey-trigger" aria-expanded={open} onClick={()=>setOpen(!open)}>Journeys to Explore <span>⌄</span></button><div className={`journey-dropdown${open?" open":""}`}><p>Choose a journey</p><a href="/journeys/east-texas"><span><strong>East Texas Escape</strong><small>Dallas to Caddo Lake · 2 days</small></span><b>↗</b></a><div className="coming-soon"><span>More journeys</span><small>Coming soon</small></div></div></div></header>
}
function Footer(){return <footer><a className="brand" href="/"><span className="brand-mark">↗</span> Have a Go</a><p>Made from miles and memories.</p><p>© {new Date().getFullYear()}</p></footer>}
function Home(){return <><Header/><main><section className="home-hero"><img src={hero} alt="A canoe gliding through cypress trees on a misty East Texas lake"/><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow">A growing travel journal</p><h1>Have a Go.</h1><p>Real journeys. Honest moments. Stories worth bringing home.</p></div></section><section className="journey-preview"><div><p className="kicker">Journey 01 · East Texas</p><h2>An East Texas Escape</h2><p>Dallas → Tyler → Lake O’ the Pines → Jefferson → Marshall → Caddo Lake</p></div><a className="explore-link" href="/journeys/east-texas">Explore the journey <span>↗</span></a></section></main><Footer/></>}
function Journey(){return <><Header/><main><section className="journey-hero"><img src={hero} alt="Cypress trees reflected in the water at Caddo Lake"/><div className="hero-shade"/><div className="journey-hero-copy"><a href="/">← All journeys</a><p className="eyebrow">Journey 01 · Two days</p><h1>An East Texas Escape</h1></div></section><section className="story"><div className="story-head"><p className="kicker">Dallas to Caddo Lake</p><h2>The road, place by place</h2><p>A short road trip filled with peaceful gardens, memorable food, a lucky lottery win, and an early-morning canoe ride.</p></div><div className="route"><span>Dallas</span><i/><span>Tyler</span><i/><span>Jefferson</span><i/><span>Marshall</span><i/><span>Caddo Lake</span></div><div className="timeline">{stops.map(s=><div key={s.number}>{s.day>0&&<div className={`day-marker${s.day===2?" second":""}`}><span>Day 0{s.day}</span><strong>{s.day===1?"Heading east":"Into the cypress"}</strong></div>}<article className={`stop ${s.tone||""}`}><span className="stop-number">{s.number}</span><a className="stop-photo" href={s.map} target="_blank"><img src={s.image} alt={s.imageAlt} loading="lazy"/></a><div><p className="place">{s.place}</p><h3>{s.title}</h3><p>{s.story}</p><a className="place-link" href={s.map} target="_blank">View location ↗</a></div></article></div>)}</div></section></main><Footer/></>}
export default function App(){return location.pathname.startsWith("/journeys/")?<Journey/>:<Home/>}
