const maps = query => `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`;
export const stops = [
  ["01",1,"Dallas → Forney","The city gives way to open road","We left Dallas with the Tesla packed. Passing through Forney, we noticed new homes, businesses, and construction changing the view mile by mile.","https://irp.cdn-website.com/c6ed7d2a/dms3rep/multi/Forney-1.jpeg","Downtown Forney mural","Forney, Texas"],
  ["02",0,"Tyler","A table at Twelve","Twelve Kitchen + Cocktails became the real beginning of the trip—a lively room, time to slow down, and a good meal.","https://cdn.slidesharecdn.com/ss_thumbnails/twelverestaurantat6minutesdrivetothewestoftylerdentistwordendentistry-221004043740-5f705668-thumbnail.jpg?fit=bounds&height=640&width=640","Twelve Kitchen and Cocktails in Tyler","Twelve Kitchen Cocktails Tyler Texas"],
  ["03",0,"Tyler Rose Garden","A quieter pace","Colorful roses and calm pathways gave us a peaceful break from the road.","https://home.nps.gov/common/uploads/cropped_image/primary/4F2AF227-F1CE-8DF1-ECF6ED135F7B7530.jpg?mode=crop&quality=90&width=1600","Tyler Municipal Rose Garden","Tyler Rose Garden Texas"],
  ["04",0,"Texas Best Smokehouse","A $12 roadside surprise","While the Tesla charged, we grabbed Starbucks and bought two $2 lottery tickets. Winning $12 turned an ordinary stop into a story.","https://www.victrongroup.com/wp-content/uploads/2024/03/DSCF9565.webp","Texas Best Smokehouse entrance","Texas Best Smokehouse Tyler Texas","accent"],
  ["05",0,"Lake O’ the Pines","Still water at Overlook Point","The open water and quiet landscape gave us a calm preview of the lake adventure still ahead.","https://lakeopinesrvpark.com/images/Ramp-2.jpg","Boat ramp at Lake O’ the Pines","Overlook Point Boat Ramp Lake O the Pines Texas"],
  ["06",0,"Jefferson","A holiday-quiet downtown","Labor Day left historic Jefferson quieter than expected, but we still enjoyed its old streets and character.","https://www.worldatlas.com/r/w768/upload/7f/4c/f5/shutterstock-1534451732.jpg","Historic downtown Jefferson, Texas","Historic Downtown Jefferson Texas"],
  ["07",0,"Chiangmai Thai Kitchen","The last table of the night","As the final customers, we enjoyed fried rice, pot stickers, Thai coconut soup, and glass noodles.","https://menufyproduction.imgix.net/638642712487797248%2B1568499.png?auto=compress%2Cformat&fit=crop&h=500&w=500","Thai food from Chiangmai Thai Kitchen","Chiangmai Thai Kitchen Tyler Texas"],
  ["08",0,"Marshall","A comfortable place to land","Holiday Inn Express & Suites was clean, neat, and good value. The polite staff made us feel welcome.","https://dimg04.c-ctrip.com/images/02Y0c12000fsazn2x0690_R_1080_808_Q90.jpg","Holiday Inn Express and Suites in Marshall","Holiday Inn Express Suites Marshall Texas"],
  ["09",2,"Johnson’s Ranch Marina · Caddo Lake","Morning by canoe","We woke early, rented a canoe, and paddled through calm water framed by cypress trees. The air began cool, but after an hour the Texas heat arrived. We returned tired, happy, and carrying the best memory of the weekend.","https://img.p.mapq.st/?q=75&url=https%3A%2F%2Fmedia-cdn.tripadvisor.com%2Fmedia%2Fphoto-o%2F24%2F88%2F01%2Ffd%2Fcaption.jpg&w=3840","Johnson’s Ranch Marina at Caddo Lake","Johnsons Ranch Marina Caddo Lake Texas","highlight"],
  ["10",0,"Joe Pine Coffee","Breakfast, art, and games","Good food, coffee, art, and games made this a relaxed final stop after the paddle.","https://tcdn.mindtrip.ai/images/16886/16886.ownlnb.jpg","A warm, art-filled coffee shop interior","Joe Pine Coffee Co Marshall Texas"],
  ["11",0,"Back to Dallas","Home with a better story","We packed up and followed the road home with photos and memories that made a short trip feel much bigger.","https://www.destinationsitters.com/Content/images/locations/destination-sitters-dallas-babysitting-service.webp","Dallas skyline at dusk","Dallas Texas","home"]
].map(([number,day,place,title,story,image,imageAlt,query,tone]) => ({number,day,place,title,story,image,imageAlt,map:maps(query),tone}));
